/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void SliderNoise(GSlider2D source, GEvent event) { //_CODE_:sliderNoise:451791:
  println("sliderNoise - GSlider2D >> GEvent." + event + " @ " + millis());
} //_CODE_:sliderNoise:451791:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  sliderNoise = new GSlider2D(this, 5, 7, 50, 50);
  sliderNoise.setLimitsX(1.0, 0.0, 1.0);
  sliderNoise.setLimitsY(0.0, 0.0, 1.0);
  sliderNoise.setNumberFormat(G4P.DECIMAL, 2);
  sliderNoise.setOpaque(true);
  sliderNoise.addEventHandler(this, "SliderNoise");
}

// Variable declarations 
// autogenerated do not edit
GSlider2D sliderNoise; 
